AllCops:
  TargetRubyVersion: 2.7

Layout/LineLength:
  Exclude:
    - spec/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Exclude:
    - spec/**/*.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

